/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-11-3")
public class DbStatusInfo implements org.apache.thrift.TBase<DbStatusInfo, DbStatusInfo._Fields>, java.io.Serializable, Cloneable, Comparable<DbStatusInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DbStatusInfo");

  private static final org.apache.thrift.protocol.TField M_DB_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("mDbStatus", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField M_DBMS_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("mDbmsInfo", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DbStatusInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DbStatusInfoTupleSchemeFactory());
  }

  /**
   * 
   * @see DbStatus
   */
  public DbStatus mDbStatus; // required
  public DbmsInfo mDbmsInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see DbStatus
     */
    M_DB_STATUS((short)1, "mDbStatus"),
    M_DBMS_INFO((short)2, "mDbmsInfo");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // M_DB_STATUS
          return M_DB_STATUS;
        case 2: // M_DBMS_INFO
          return M_DBMS_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.M_DB_STATUS, new org.apache.thrift.meta_data.FieldMetaData("mDbStatus", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, DbStatus.class)));
    tmpMap.put(_Fields.M_DBMS_INFO, new org.apache.thrift.meta_data.FieldMetaData("mDbmsInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DbmsInfo.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DbStatusInfo.class, metaDataMap);
  }

  public DbStatusInfo() {
  }

  public DbStatusInfo(
    DbStatus mDbStatus,
    DbmsInfo mDbmsInfo)
  {
    this();
    this.mDbStatus = mDbStatus;
    this.mDbmsInfo = mDbmsInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DbStatusInfo(DbStatusInfo other) {
    if (other.isSetMDbStatus()) {
      this.mDbStatus = other.mDbStatus;
    }
    if (other.isSetMDbmsInfo()) {
      this.mDbmsInfo = new DbmsInfo(other.mDbmsInfo);
    }
  }

  public DbStatusInfo deepCopy() {
    return new DbStatusInfo(this);
  }

  @Override
  public void clear() {
    this.mDbStatus = null;
    this.mDbmsInfo = null;
  }

  /**
   * 
   * @see DbStatus
   */
  public DbStatus getMDbStatus() {
    return this.mDbStatus;
  }

  /**
   * 
   * @see DbStatus
   */
  public DbStatusInfo setMDbStatus(DbStatus mDbStatus) {
    this.mDbStatus = mDbStatus;
    return this;
  }

  public void unsetMDbStatus() {
    this.mDbStatus = null;
  }

  /** Returns true if field mDbStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetMDbStatus() {
    return this.mDbStatus != null;
  }

  public void setMDbStatusIsSet(boolean value) {
    if (!value) {
      this.mDbStatus = null;
    }
  }

  public DbmsInfo getMDbmsInfo() {
    return this.mDbmsInfo;
  }

  public DbStatusInfo setMDbmsInfo(DbmsInfo mDbmsInfo) {
    this.mDbmsInfo = mDbmsInfo;
    return this;
  }

  public void unsetMDbmsInfo() {
    this.mDbmsInfo = null;
  }

  /** Returns true if field mDbmsInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetMDbmsInfo() {
    return this.mDbmsInfo != null;
  }

  public void setMDbmsInfoIsSet(boolean value) {
    if (!value) {
      this.mDbmsInfo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case M_DB_STATUS:
      if (value == null) {
        unsetMDbStatus();
      } else {
        setMDbStatus((DbStatus)value);
      }
      break;

    case M_DBMS_INFO:
      if (value == null) {
        unsetMDbmsInfo();
      } else {
        setMDbmsInfo((DbmsInfo)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case M_DB_STATUS:
      return getMDbStatus();

    case M_DBMS_INFO:
      return getMDbmsInfo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case M_DB_STATUS:
      return isSetMDbStatus();
    case M_DBMS_INFO:
      return isSetMDbmsInfo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DbStatusInfo)
      return this.equals((DbStatusInfo)that);
    return false;
  }

  public boolean equals(DbStatusInfo that) {
    if (that == null)
      return false;

    boolean this_present_mDbStatus = true && this.isSetMDbStatus();
    boolean that_present_mDbStatus = true && that.isSetMDbStatus();
    if (this_present_mDbStatus || that_present_mDbStatus) {
      if (!(this_present_mDbStatus && that_present_mDbStatus))
        return false;
      if (!this.mDbStatus.equals(that.mDbStatus))
        return false;
    }

    boolean this_present_mDbmsInfo = true && this.isSetMDbmsInfo();
    boolean that_present_mDbmsInfo = true && that.isSetMDbmsInfo();
    if (this_present_mDbmsInfo || that_present_mDbmsInfo) {
      if (!(this_present_mDbmsInfo && that_present_mDbmsInfo))
        return false;
      if (!this.mDbmsInfo.equals(that.mDbmsInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_mDbStatus = true && (isSetMDbStatus());
    list.add(present_mDbStatus);
    if (present_mDbStatus)
      list.add(mDbStatus.getValue());

    boolean present_mDbmsInfo = true && (isSetMDbmsInfo());
    list.add(present_mDbmsInfo);
    if (present_mDbmsInfo)
      list.add(mDbmsInfo);

    return list.hashCode();
  }

  @Override
  public int compareTo(DbStatusInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMDbStatus()).compareTo(other.isSetMDbStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMDbStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mDbStatus, other.mDbStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMDbmsInfo()).compareTo(other.isSetMDbmsInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMDbmsInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mDbmsInfo, other.mDbmsInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DbStatusInfo(");
    boolean first = true;

    sb.append("mDbStatus:");
    if (this.mDbStatus == null) {
      sb.append("null");
    } else {
      sb.append(this.mDbStatus);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("mDbmsInfo:");
    if (this.mDbmsInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.mDbmsInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (mDbmsInfo != null) {
      mDbmsInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DbStatusInfoStandardSchemeFactory implements SchemeFactory {
    public DbStatusInfoStandardScheme getScheme() {
      return new DbStatusInfoStandardScheme();
    }
  }

  private static class DbStatusInfoStandardScheme extends StandardScheme<DbStatusInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DbStatusInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // M_DB_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.mDbStatus = thrift.DbStatus.findByValue(iprot.readI32());
              struct.setMDbStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // M_DBMS_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.mDbmsInfo = new DbmsInfo();
              struct.mDbmsInfo.read(iprot);
              struct.setMDbmsInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DbStatusInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.mDbStatus != null) {
        oprot.writeFieldBegin(M_DB_STATUS_FIELD_DESC);
        oprot.writeI32(struct.mDbStatus.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.mDbmsInfo != null) {
        oprot.writeFieldBegin(M_DBMS_INFO_FIELD_DESC);
        struct.mDbmsInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DbStatusInfoTupleSchemeFactory implements SchemeFactory {
    public DbStatusInfoTupleScheme getScheme() {
      return new DbStatusInfoTupleScheme();
    }
  }

  private static class DbStatusInfoTupleScheme extends TupleScheme<DbStatusInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DbStatusInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMDbStatus()) {
        optionals.set(0);
      }
      if (struct.isSetMDbmsInfo()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMDbStatus()) {
        oprot.writeI32(struct.mDbStatus.getValue());
      }
      if (struct.isSetMDbmsInfo()) {
        struct.mDbmsInfo.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DbStatusInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.mDbStatus = thrift.DbStatus.findByValue(iprot.readI32());
        struct.setMDbStatusIsSet(true);
      }
      if (incoming.get(1)) {
        struct.mDbmsInfo = new DbmsInfo();
        struct.mDbmsInfo.read(iprot);
        struct.setMDbmsInfoIsSet(true);
      }
    }
  }

}

