/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum DType implements org.apache.thrift.TEnum {
  INT(0),
  FLOAT(1),
  VARCHAR(2);

  private final int value;

  private DType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DType findByValue(int value) { 
    switch (value) {
      case 0:
        return INT;
      case 1:
        return FLOAT;
      case 2:
        return VARCHAR;
      default:
        return null;
    }
  }
}
