/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OperationType implements org.apache.thrift.TEnum {
  TABLE_CREATE(1),
  TABLE_DROP(2),
  EXECUTE_SQL(3);

  private final int value;

  private OperationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OperationType findByValue(int value) { 
    switch (value) {
      case 1:
        return TABLE_CREATE;
      case 2:
        return TABLE_DROP;
      case 3:
        return EXECUTE_SQL;
      default:
        return null;
    }
  }
}
