/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-29")
public class TableOperationPara implements org.apache.thrift.TBase<TableOperationPara, TableOperationPara._Fields>, java.io.Serializable, Cloneable, Comparable<TableOperationPara> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TableOperationPara");

  private static final org.apache.thrift.protocol.TField M_TENANT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("mTenantID", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField M_TABLE_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("mTableInfo", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TableOperationParaStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TableOperationParaTupleSchemeFactory());
  }

  public int mTenantID; // required
  public TableInfo mTableInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    M_TENANT_ID((short)1, "mTenantID"),
    M_TABLE_INFO((short)2, "mTableInfo");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // M_TENANT_ID
          return M_TENANT_ID;
        case 2: // M_TABLE_INFO
          return M_TABLE_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MTENANTID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.M_TENANT_ID, new org.apache.thrift.meta_data.FieldMetaData("mTenantID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.M_TABLE_INFO, new org.apache.thrift.meta_data.FieldMetaData("mTableInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TableInfo.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TableOperationPara.class, metaDataMap);
  }

  public TableOperationPara() {
  }

  public TableOperationPara(
    int mTenantID,
    TableInfo mTableInfo)
  {
    this();
    this.mTenantID = mTenantID;
    setMTenantIDIsSet(true);
    this.mTableInfo = mTableInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TableOperationPara(TableOperationPara other) {
    __isset_bitfield = other.__isset_bitfield;
    this.mTenantID = other.mTenantID;
    if (other.isSetMTableInfo()) {
      this.mTableInfo = new TableInfo(other.mTableInfo);
    }
  }

  public TableOperationPara deepCopy() {
    return new TableOperationPara(this);
  }

  @Override
  public void clear() {
    setMTenantIDIsSet(false);
    this.mTenantID = 0;
    this.mTableInfo = null;
  }

  public int getMTenantID() {
    return this.mTenantID;
  }

  public TableOperationPara setMTenantID(int mTenantID) {
    this.mTenantID = mTenantID;
    setMTenantIDIsSet(true);
    return this;
  }

  public void unsetMTenantID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MTENANTID_ISSET_ID);
  }

  /** Returns true if field mTenantID is set (has been assigned a value) and false otherwise */
  public boolean isSetMTenantID() {
    return EncodingUtils.testBit(__isset_bitfield, __MTENANTID_ISSET_ID);
  }

  public void setMTenantIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MTENANTID_ISSET_ID, value);
  }

  public TableInfo getMTableInfo() {
    return this.mTableInfo;
  }

  public TableOperationPara setMTableInfo(TableInfo mTableInfo) {
    this.mTableInfo = mTableInfo;
    return this;
  }

  public void unsetMTableInfo() {
    this.mTableInfo = null;
  }

  /** Returns true if field mTableInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetMTableInfo() {
    return this.mTableInfo != null;
  }

  public void setMTableInfoIsSet(boolean value) {
    if (!value) {
      this.mTableInfo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case M_TENANT_ID:
      if (value == null) {
        unsetMTenantID();
      } else {
        setMTenantID((Integer)value);
      }
      break;

    case M_TABLE_INFO:
      if (value == null) {
        unsetMTableInfo();
      } else {
        setMTableInfo((TableInfo)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case M_TENANT_ID:
      return Integer.valueOf(getMTenantID());

    case M_TABLE_INFO:
      return getMTableInfo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case M_TENANT_ID:
      return isSetMTenantID();
    case M_TABLE_INFO:
      return isSetMTableInfo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TableOperationPara)
      return this.equals((TableOperationPara)that);
    return false;
  }

  public boolean equals(TableOperationPara that) {
    if (that == null)
      return false;

    boolean this_present_mTenantID = true;
    boolean that_present_mTenantID = true;
    if (this_present_mTenantID || that_present_mTenantID) {
      if (!(this_present_mTenantID && that_present_mTenantID))
        return false;
      if (this.mTenantID != that.mTenantID)
        return false;
    }

    boolean this_present_mTableInfo = true && this.isSetMTableInfo();
    boolean that_present_mTableInfo = true && that.isSetMTableInfo();
    if (this_present_mTableInfo || that_present_mTableInfo) {
      if (!(this_present_mTableInfo && that_present_mTableInfo))
        return false;
      if (!this.mTableInfo.equals(that.mTableInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_mTenantID = true;
    list.add(present_mTenantID);
    if (present_mTenantID)
      list.add(mTenantID);

    boolean present_mTableInfo = true && (isSetMTableInfo());
    list.add(present_mTableInfo);
    if (present_mTableInfo)
      list.add(mTableInfo);

    return list.hashCode();
  }

  @Override
  public int compareTo(TableOperationPara other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMTenantID()).compareTo(other.isSetMTenantID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMTenantID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mTenantID, other.mTenantID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMTableInfo()).compareTo(other.isSetMTableInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMTableInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mTableInfo, other.mTableInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TableOperationPara(");
    boolean first = true;

    sb.append("mTenantID:");
    sb.append(this.mTenantID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("mTableInfo:");
    if (this.mTableInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.mTableInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (mTableInfo != null) {
      mTableInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TableOperationParaStandardSchemeFactory implements SchemeFactory {
    public TableOperationParaStandardScheme getScheme() {
      return new TableOperationParaStandardScheme();
    }
  }

  private static class TableOperationParaStandardScheme extends StandardScheme<TableOperationPara> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TableOperationPara struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // M_TENANT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.mTenantID = iprot.readI32();
              struct.setMTenantIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // M_TABLE_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.mTableInfo = new TableInfo();
              struct.mTableInfo.read(iprot);
              struct.setMTableInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TableOperationPara struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(M_TENANT_ID_FIELD_DESC);
      oprot.writeI32(struct.mTenantID);
      oprot.writeFieldEnd();
      if (struct.mTableInfo != null) {
        oprot.writeFieldBegin(M_TABLE_INFO_FIELD_DESC);
        struct.mTableInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TableOperationParaTupleSchemeFactory implements SchemeFactory {
    public TableOperationParaTupleScheme getScheme() {
      return new TableOperationParaTupleScheme();
    }
  }

  private static class TableOperationParaTupleScheme extends TupleScheme<TableOperationPara> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TableOperationPara struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMTenantID()) {
        optionals.set(0);
      }
      if (struct.isSetMTableInfo()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMTenantID()) {
        oprot.writeI32(struct.mTenantID);
      }
      if (struct.isSetMTableInfo()) {
        struct.mTableInfo.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TableOperationPara struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.mTenantID = iprot.readI32();
        struct.setMTenantIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.mTableInfo = new TableInfo();
        struct.mTableInfo.read(iprot);
        struct.setMTableInfoIsSet(true);
      }
    }
  }

}

