/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-9-17")
public class TempTableInfo implements org.apache.thrift.TBase<TempTableInfo, TempTableInfo._Fields>, java.io.Serializable, Cloneable, Comparable<TempTableInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TempTableInfo");

  private static final org.apache.thrift.protocol.TField M_TABLE_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("mTableInfo", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField M_TABLE_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("mTablePath", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TempTableInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TempTableInfoTupleSchemeFactory());
  }

  public TableInfo mTableInfo; // required
  public String mTablePath; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    M_TABLE_INFO((short)1, "mTableInfo"),
    M_TABLE_PATH((short)2, "mTablePath");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // M_TABLE_INFO
          return M_TABLE_INFO;
        case 2: // M_TABLE_PATH
          return M_TABLE_PATH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.M_TABLE_INFO, new org.apache.thrift.meta_data.FieldMetaData("mTableInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TableInfo.class)));
    tmpMap.put(_Fields.M_TABLE_PATH, new org.apache.thrift.meta_data.FieldMetaData("mTablePath", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TempTableInfo.class, metaDataMap);
  }

  public TempTableInfo() {
  }

  public TempTableInfo(
    TableInfo mTableInfo,
    String mTablePath)
  {
    this();
    this.mTableInfo = mTableInfo;
    this.mTablePath = mTablePath;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TempTableInfo(TempTableInfo other) {
    if (other.isSetMTableInfo()) {
      this.mTableInfo = new TableInfo(other.mTableInfo);
    }
    if (other.isSetMTablePath()) {
      this.mTablePath = other.mTablePath;
    }
  }

  public TempTableInfo deepCopy() {
    return new TempTableInfo(this);
  }

  @Override
  public void clear() {
    this.mTableInfo = null;
    this.mTablePath = null;
  }

  public TableInfo getMTableInfo() {
    return this.mTableInfo;
  }

  public TempTableInfo setMTableInfo(TableInfo mTableInfo) {
    this.mTableInfo = mTableInfo;
    return this;
  }

  public void unsetMTableInfo() {
    this.mTableInfo = null;
  }

  /** Returns true if field mTableInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetMTableInfo() {
    return this.mTableInfo != null;
  }

  public void setMTableInfoIsSet(boolean value) {
    if (!value) {
      this.mTableInfo = null;
    }
  }

  public String getMTablePath() {
    return this.mTablePath;
  }

  public TempTableInfo setMTablePath(String mTablePath) {
    this.mTablePath = mTablePath;
    return this;
  }

  public void unsetMTablePath() {
    this.mTablePath = null;
  }

  /** Returns true if field mTablePath is set (has been assigned a value) and false otherwise */
  public boolean isSetMTablePath() {
    return this.mTablePath != null;
  }

  public void setMTablePathIsSet(boolean value) {
    if (!value) {
      this.mTablePath = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case M_TABLE_INFO:
      if (value == null) {
        unsetMTableInfo();
      } else {
        setMTableInfo((TableInfo)value);
      }
      break;

    case M_TABLE_PATH:
      if (value == null) {
        unsetMTablePath();
      } else {
        setMTablePath((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case M_TABLE_INFO:
      return getMTableInfo();

    case M_TABLE_PATH:
      return getMTablePath();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case M_TABLE_INFO:
      return isSetMTableInfo();
    case M_TABLE_PATH:
      return isSetMTablePath();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TempTableInfo)
      return this.equals((TempTableInfo)that);
    return false;
  }

  public boolean equals(TempTableInfo that) {
    if (that == null)
      return false;

    boolean this_present_mTableInfo = true && this.isSetMTableInfo();
    boolean that_present_mTableInfo = true && that.isSetMTableInfo();
    if (this_present_mTableInfo || that_present_mTableInfo) {
      if (!(this_present_mTableInfo && that_present_mTableInfo))
        return false;
      if (!this.mTableInfo.equals(that.mTableInfo))
        return false;
    }

    boolean this_present_mTablePath = true && this.isSetMTablePath();
    boolean that_present_mTablePath = true && that.isSetMTablePath();
    if (this_present_mTablePath || that_present_mTablePath) {
      if (!(this_present_mTablePath && that_present_mTablePath))
        return false;
      if (!this.mTablePath.equals(that.mTablePath))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_mTableInfo = true && (isSetMTableInfo());
    list.add(present_mTableInfo);
    if (present_mTableInfo)
      list.add(mTableInfo);

    boolean present_mTablePath = true && (isSetMTablePath());
    list.add(present_mTablePath);
    if (present_mTablePath)
      list.add(mTablePath);

    return list.hashCode();
  }

  @Override
  public int compareTo(TempTableInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMTableInfo()).compareTo(other.isSetMTableInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMTableInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mTableInfo, other.mTableInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMTablePath()).compareTo(other.isSetMTablePath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMTablePath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mTablePath, other.mTablePath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TempTableInfo(");
    boolean first = true;

    sb.append("mTableInfo:");
    if (this.mTableInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.mTableInfo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("mTablePath:");
    if (this.mTablePath == null) {
      sb.append("null");
    } else {
      sb.append(this.mTablePath);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (mTableInfo != null) {
      mTableInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TempTableInfoStandardSchemeFactory implements SchemeFactory {
    public TempTableInfoStandardScheme getScheme() {
      return new TempTableInfoStandardScheme();
    }
  }

  private static class TempTableInfoStandardScheme extends StandardScheme<TempTableInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TempTableInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // M_TABLE_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.mTableInfo = new TableInfo();
              struct.mTableInfo.read(iprot);
              struct.setMTableInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // M_TABLE_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mTablePath = iprot.readString();
              struct.setMTablePathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TempTableInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.mTableInfo != null) {
        oprot.writeFieldBegin(M_TABLE_INFO_FIELD_DESC);
        struct.mTableInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.mTablePath != null) {
        oprot.writeFieldBegin(M_TABLE_PATH_FIELD_DESC);
        oprot.writeString(struct.mTablePath);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TempTableInfoTupleSchemeFactory implements SchemeFactory {
    public TempTableInfoTupleScheme getScheme() {
      return new TempTableInfoTupleScheme();
    }
  }

  private static class TempTableInfoTupleScheme extends TupleScheme<TempTableInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TempTableInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMTableInfo()) {
        optionals.set(0);
      }
      if (struct.isSetMTablePath()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMTableInfo()) {
        struct.mTableInfo.write(oprot);
      }
      if (struct.isSetMTablePath()) {
        oprot.writeString(struct.mTablePath);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TempTableInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.mTableInfo = new TableInfo();
        struct.mTableInfo.read(iprot);
        struct.setMTableInfoIsSet(true);
      }
      if (incoming.get(1)) {
        struct.mTablePath = iprot.readString();
        struct.setMTablePathIsSet(true);
      }
    }
  }

}

