/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Type implements org.apache.thrift.TEnum {
  TINY_INT(0),
  SMALL_INT(1),
  INT(2),
  BIG_INT(3),
  DECIMAL(4),
  FLOAT(5),
  VARCHAR(6),
  TIMESTAMP(7);

  private final int value;

  private Type(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Type findByValue(int value) { 
    switch (value) {
      case 0:
        return TINY_INT;
      case 1:
        return SMALL_INT;
      case 2:
        return INT;
      case 3:
        return BIG_INT;
      case 4:
        return DECIMAL;
      case 5:
        return FLOAT;
      case 6:
        return VARCHAR;
      case 7:
        return TIMESTAMP;
      default:
        return null;
    }
  }
}
